apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: project
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  type: ClusterIP
