apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: project
spec:
  replicas: 1
  updateStrategy:
    type: OnDelete
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 80 # Internal port that is exposed
      targetPort: 5000 # Port flask listens to
