apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
  labels:
    app: todo-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
      - name: todo-app
        image: gcr.io/YOUR_PROJECT_ID/todo-app:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-image
          mountPath: /shared
        env:
        - name: PORT
          value: "5000"
        - name: TODO_BACKEND_URL
          value: "http://todo-backend-svc:5000"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
