apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - g_manifests/deployment.yaml
  - g_manifests/service.yaml
  - g_manifests/secrets.yaml
  - g_manifests/ingress.yaml

images:
  - name: ping-pong         
    newName: macrichard/ping-pong
    newTag: "4.7"
