apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
      - name: todo-app
        image: macrichard/todo-app:5.3
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-image
          mountPath: /shared
        env:
        - name: PORT
          value: "5000"
        - name: "TODO_BACKEND_URL"
          value: "http://todo-backend-svc:5000"
