apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000 
