apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
      - name: ping-pong
        image: macrichard/ping-pong:2.0
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        ports:
        - containerPort: 5000
