apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: macrichard/log-output:4.3
        imagePullPolicy: Always
        env:
        - name: PINGPONG_URL
          valueFrom:
            secretKeyRef:
              name: log-output-secrets
              key: PINGPONG_URL
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: log-output-config
              key: MESSAGE
        volumeMounts:
        - name: config-volume
          mountPath: /config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: log-output-config
