apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
