apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: appnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: macrichard/ping-pong:3.0
        ports:
        - containerPort: 5000
