apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: appnamespace
  labels:
    app: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: macrichard/ping-pong:4.6
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DATABASE_NAME
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DATABASE_HOST
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"
