apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: appnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: macrichard/log-output:4.1
        env:
        - name: DATABASE_URL
          value: "postgresql://pingpong:securepassword@postgres-svc:5432/pingpongdb"
        ports:
        - containerPort: 5000
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: log-output-config
              key: MESSAGE
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: log-output-config
