name: Deploy part3 to GKE

on:
  push:
    paths:
      - "part3/**"
      - ".github/**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGEBACKEND: todo-backend
  IMAGEFRONT: todo-app
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Configure Docker for GCP
        run: gcloud --quiet auth configure-docker

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate with GKE
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Push Todo Backend Image
        run: |
          docker build --platform=linux/amd64 \
            --tag "gcr.io/$PROJECT_ID/$IMAGEBACKEND:$BRANCH-$GITHUB_SHA" \
            ./part3/todo/todo_backend
          docker push "gcr.io/$PROJECT_ID/$IMAGEBACKEND:$BRANCH-$GITHUB_SHA"

      - name: Build and Push Todo App Image
        run: |
          docker build --platform=linux/amd64 \
            --tag "gcr.io/$PROJECT_ID/$IMAGEFRONT:$BRANCH-$GITHUB_SHA" \
            ./part3/todo/todo_app
          docker push "gcr.io/$PROJECT_ID/$IMAGEFRONT:$BRANCH-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Set up SOPS
        uses: nhedger/setup-sops@v2

      - name: Decrypt and Apply Secret
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH_NAME" = "main" ]; then
            NAMESPACE="default"
          else
            NAMESPACE="$BRANCH_NAME"
            kubectl create namespace "$NAMESPACE" || true
          fi
          kubectl config set-context --current --namespace="$NAMESPACE"
          sops --decrypt part3/todo/manifests/secret.enc.yaml > part3/todo/manifests/secret.yaml
          kubectl apply -f part3/todo/manifests/secret.yaml

      - name: Deploy
        run: |
          cd ./part3/todo
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          kustomize edit set image PROJECT/IMAGEBACK=gcr.io/$PROJECT_ID/$IMAGEBACKEND:$BRANCH-$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGEFRONT=gcr.io/$PROJECT_ID/$IMAGEFRONT:$BRANCH-$GITHUB_SHA
          if [ "$BRANCH_NAME" = "main" ]; then
            NAMESPACE="default"
          else
            NAMESPACE="$BRANCH_NAME"
          fi
          kubectl config set-context --current --namespace="$NAMESPACE"
          kustomize edit set namespace "$NAMESPACE"
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$IMAGEBACKEND -n project
          kubectl rollout status deployment/$IMAGEFRONT -n project
          kubectl get services -o wide
