name: Deploy part3 to GKE

on:
  push:
    paths:
      - "part3/**" # Trigger workflow only for changes under part3
      - ".github/**"      # Trigger when changes are made to the workflow files

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  
jobs:
  build-publish-deploy:
    name: Build, Publish, and Deploy part3 to GKE
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Setup Docker Authentication
        run: gcloud --quiet auth configure-docker

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate with GKE
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Build and Push Todo Backend Image
        run: |-
          docker build --platform=linux/amd64 -t gcr.io/${{ secrets.GKE_PROJECT }}/todo-backend:${{ github.sha }} ./part3/todo/todo_backend
          docker push gcr.io/${{ secrets.GKE_PROJECT }}/todo-backend:${{ github.sha }}

      - name: Build and Push Todo App Image
        run: |-
          docker build --platform=linux/amd64 -t gcr.io/${{ secrets.GKE_PROJECT }}/todo-app:${{ github.sha }} ./part3/todo/todo_app
          docker push gcr.io/${{ secrets.GKE_PROJECT }}/todo-app:${{ github.sha }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy part3 with Kustomize
        run: |-
          cd ./part3/todo
          kustomize edit set image gcr.io/${{ secrets.GKE_PROJECT }}/todo-backend:${{ github.sha }}
          kustomize edit set image gcr.io/${{ secrets.GKE_PROJECT }}/todo-app:${{ github.sha }}
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/todo-backend -n project
          kubectl rollout status deployment/todo-app -n project
