name: Build and Deploy Pingpong

on:
  push:
    paths:
      - 'part4/pingpong/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t macrichard/ping-pong:${GITHUB_SHA} part4/pingpong
          docker push macrichard/ping-pong:${GITHUB_SHA}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomization.yaml with new image
        working-directory: part4/pingpong
        run: |
          kustomize edit set image PROJECT/IMAGE=macrichard/ping-pong:${GITHUB_SHA}

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          cwd: part4/pingpong
          add: 'kustomization.yaml'
          message: "pingpong: update image to ${{ github.sha }}"
          push: true
